package servererrors

import "errors"

var (
	ErrorUnknown                  = errors.New("unknown error")
	ErrorIncorrectEmailOrPassword = errors.New("incorrect email or password")
	ErrorUserNotActivated         = errors.New("user not activated")
	ErrorLogin                    = errors.New("incorrect login information")
	ErrorSession                  = errors.New("session error")
	ErrorAuthToken                = errors.New("auth token error")
	ErrorRefreshToken             = errors.New("refresh token error")
	ErrorExpiredRefreshToken      = errors.New("refresh token expired")
	ErrorDataBaseQuery            = errors.New("invalid database query")
	Error2FAAuth                  = errors.New("2fa not authenticated")
	Error2FANotRegistered         = errors.New("2fa token not registered")
	ErrorUserIsExist              = errors.New("user is exist")
	ErrorSendMessageToTelegram    = errors.New("the message was not sent")
	ErrorInvalidRequest           = errors.New("invalid data in the request")
	ErrorNotAuthenticated         = errors.New("not authenticated")
	ErrorRecordNotFound           = errors.New("record not found")
	ErrorRecordNotAdd             = errors.New("record not added")
	ErrorExpiredAuthToken         = errors.New("auth token expired")
	ErrorInvalidToken             = errors.New("invalid token")
	ErrorInternal                 = errors.New("internal server error")
	ErrorAccessDeined             = errors.New("access is denied")
	ErrorBase64                   = errors.New("invalid base64 format")
	ErrorACERemoveAdmin           = errors.New("can't remove admin ace")
	ErrorRecordNotCreated         = errors.New("record not created")
	ErrorInvalidData              = errors.New("invalid data")
	ErrorProcessAlreadyRunning    = errors.New("process already running error")
	ErrorProcessNotFound          = errors.New("process not found")
	ErrorAccessDenied             = errors.New("access denied")
	ErrorSocketReqContext         = errors.New("initialize socket request context")
	ErrorSocketUnknownHandler     = errors.New("unknown socket handler")
	ErrorUnknownTypeRequest       = errors.New("unknown type request")
)
